---
# tasks file for yolo-client
    - name: Pull Docker image
      docker_image:
        name: ivymachogu/yolo-client:v1.1.1
        source: pull   

    - name: Run Docker container
      docker_container:
        name: yolo-client
        image: ivymachogu/yolo-client:v1.1.1
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
