apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:   
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb-port
          
        volumeMounts:
        - name: yolo-pvc
          mountPath: /data/db

      
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb-service:27017
      
  volumeClaimTemplates:
  - metadata:
      name: yolo-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

  
