apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-backend-config
data:
  backend.conf: |
    database:
      uri: mongodb://mongodb-service:27017
    server:
      port: 5000
    security:
      enableAuth: false

