apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: yolo-client
        image: ivymachogu/yolo-client:v1.1.1 
        ports:
        - containerPort: 3000
        tty: true 
        stdin: true 

